apiVersion: v1
kind: Service
metadata:
  name: employee-mgmt-service
  namespace: gerald-env 
  labels:
    app: employee-mgmt
spec:
  type: LoadBalancer 
  selector:
    app: employee-mgmt
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080 
